### ISSUE TITLE
Integrate AllDomains into Realms

### ISSUE THREAD

**Issue by metasal1** [Mythic-Project/governance-ui#45]
We require the following 5 actions to be possible on realms.today

1. Create DAO Step 2

https://app.realms.today/realms/new/multisig

Allow the user to enter the Alldomains domain to lookup the wallet address for the member to be invited
![image](https://github.com/user-attachments/assets/85aae118-76f9-4c44-9883-63904cbc74f6)

2. Members Page

Display user’s domain

[https://app.realms.today/dao/{daoname}/members](https://app.realms.today/dao/%7Bdaoname%7D/members)

![image](https://github.com/user-attachments/assets/bee0a138-c517-4d10-8697-fd6cd8c1cc90)

3. Add Member

Enter by AD username

[https://app.realms.today/dao/{dao name}/members](https://app.realms.today/dao/%7Bdaoname%7D/members)

![image](https://github.com/user-attachments/assets/13d6f568-1e23-4565-9c62-2d818edde1fa)

4. New Proposal

Whenever the UI expects a Member’s wallet, present option to enter AD username

[https://app.realms.today/dao/{daoname}/proposal/new](https://app.realms.today/dao/%7Bdaoname%7D/proposal/new)

![image](https://github.com/user-attachments/assets/bfb774c0-a311-42bc-9096-9c3ea7c5a3ae)

5. Show Domains

Show list of domains owned by the DAO

[https://app.realms.today/dao/{dao name}/treasury/v2](https://app.realms.today/dao/%7Bdao%7D/treasury/v2)

- Display domains
- Transfer domain
- Visit domain
![image](https://github.com/user-attachments/assets/e49320d7-18f0-4303-ac20-ff62351a41fc)

**References**

- [AllDomains SDK](https://docs.alldomains.id/protocol/developer-guide/ad-sdk)

- [Realms Governance Repo](https://github.com/Mythic-Project/governance-ui)

**Comment by 0xShuk** [comment]
The issue has been resolved with PR #49
